id: hl7.fhir.ee.base
canonical: https://fhir.ee
name: EEBase
title: Estonian Base Implementation Guide
description: Eesti FHIR standardi baas juurutusjuhend
status: draft # draft | active | retired | unknown
version: 1.0.0
fhirVersion: 5.0.0 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2023+
releaseLabel: ballot # ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
license: Apache-2.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
jurisdiction: urn:iso:std:iso:3166#EE "Estonia" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: HL7 Estonia
  url: https://www.hl7.ee
  # email: test@example.org

pages:
  testlehekulg.md:
    title: testlehekülg
  test-page.md:
    title: Test page
  test-lehekulje-alamlehekulg.md:
    title: Test lehekülje alamlehekülg
  subpage-of-test-page.md:
    title: Subpage of test page
  kesjgheri.md:
    title: kesjgheri
  sgerge.md:
    title: sgerge
  pikk-hierarhia.md:
    title: pikk-hierarhia
  long-hierarchy.md:
    title: long-hierarchy
  wesgerreye.md:
    title: wesgerreye
  wesgerrey-et.md:
    title: wesgerrey-et
  aaaaa.md:
    title: aaaaa
  bmi-test.md:
    title: BMI test
  related-person-test.md:
    title: Related Person Test
  allergy.md:
    title: Allergy
  kontaktisik.md:
    title: Kontaktisik
  mammograafia.md:
    title: Mammograafia
  contact-person.md:
    title: Contact person
  medications.md:
    title: Medications
  ravimid.md:
    title: Ravimid

menu:
  Home: test-page.html
  test: 
    Ravimid: medications.html
    sss: subpage-of-test-page.html