id: hl7.fhir.ee.base
canonical: https://fhir.ee
name: EEBase
title: Estonian Base Implementation Guide
description: Eesti FHIR standardi baas juurutusjuhend
status: draft # draft | active | retired | unknown
version: 1.0.0
fhirVersion: 5.0.0 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2023+
releaseLabel: ballot # ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
license: Apache-2.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
jurisdiction: urn:iso:std:iso:3166#EE "Estonia" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: HL7 Estonia
  url: https://www.hl7.ee
  # email: test@example.org

pages:
  testlehekulg.md:
    testlehekülg
  test-page.md:
    Test page
  test-lehekulje-alamlehekulg.md:
    Test lehekülje alamlehekülg
  subpage-of-test-page.md:
    Subpage of test page
  kesjgheri.md:
    kesjgheri
  sgerge.md:
    sgerge
  pikk-hierarhia.md:
    pikk-hierarhia
  long-hierarchy.md:
    long-hierarchy
  wesgerreye.md:
    wesgerreye
  wesgerrey-et.md:
    wesgerrey-et
  aaaaa.md:
    aaaaa
  bmi-test.md:
    BMI test
  related-person-test.md:
    Related Person Test
  allergy.md:
    Allergy
  kontaktisik.md:
    Kontaktisik
  mammograafia.md:
    Mammograafia
  contact-person.md:
    Contact person
  medications.md:
    Medications
  ravimid.md:
    Ravimid

menu:
  Home: test-page.html
  test: 
    Ravimid: medications.html
    sss: subpage-of-test-page.html